# Generated by Django 5.2.5 on 2025-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
    ]
